name: CI
on:

  push:
    branches:
      - main
      
  schedule:
    - cron: "*/5 * * * *"

jobs:

  autoPush:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run and Push
      run: |
        npm start
        git add .
        git commit -m "commit"
        git push
